# Generated by Django 5.2 on 2025-04-08 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=100)),
                ('yurt', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Onum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=100)),
                ('baha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowda.kategoriya')),
            ],
            options={
                'verbose_name_plural': 'Onumler',
            },
        ),
        migrations.CreateModel(
            name='ImportHasabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mukdary', models.PositiveIntegerField()),
                ('ýurt', models.CharField(max_length=100)),
                ('senesi', models.DateField(auto_now_add=True)),
                ('onum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowda.onum')),
            ],
        ),
        migrations.CreateModel(
            name='Ammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mukdary', models.PositiveIntegerField()),
                ('yerlesyan_yeri', models.CharField(max_length=100)),
                ('onum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sowda.onum')),
            ],
            options={
                'verbose_name_plural': 'Ammar',
            },
        ),
        migrations.CreateModel(
            name='EksportSargyt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mukdary', models.PositiveIntegerField()),
                ('senesi', models.DateField(auto_now_add=True)),
                ('onum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowda.onum')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowda.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Sargyt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('müşderi_ady', models.CharField(max_length=100)),
                ('ýer', models.CharField(max_length=100)),
                ('mukdary', models.PositiveIntegerField()),
                ('baha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('senesi', models.DateField(auto_now_add=True)),
                ('onum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowda.onum')),
            ],
            options={
                'verbose_name_plural': 'Sargytlar',
            },
        ),
    ]
