# Generated by Django 5.2 on 2025-04-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eksportsargyt',
            options={'verbose_name_plural': 'Eksport Sargytlar'},
        ),
        migrations.AlterModelOptions(
            name='importhasabat',
            options={'verbose_name_plural': 'Import Hasabatlar'},
        ),
        migrations.RemoveField(
            model_name='importhasabat',
            name='ýurt',
        ),
        migrations.AddField(
            model_name='importhasabat',
            name='baha',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
