# Generated by Django 5.2 on 2025-04-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowda', '0002_alter_eksportsargyt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onum',
            name='suraty',
            field=models.ImageField(blank=True, null=True, upload_to='onum_suraty/'),
        ),
        migrations.AlterField(
            model_name='importhasabat',
            name='baha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
