# Generated by Django 5.2 on 2025-04-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowda', '0003_onum_suraty_alter_importhasabat_baha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onum',
            name='suraty',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
