# Generated by Django 5.2 on 2025-04-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowda', '0004_alter_onum_suraty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ammar',
            name='yerlesyan_yeri',
        ),
    ]
