# Generated by Django 5.2 on 2025-04-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowda', '0005_remove_ammar_yerlesyan_yeri'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partner',
            new_name='Alyjy',
        ),
        migrations.AlterModelOptions(
            name='alyjy',
            options={'verbose_name_plural': 'Alyjylar'},
        ),
    ]
